import {getLinkToFnForRoutesStatement} from "./get-link-helper";
import {getRouteListStatement, readRoutes} from "./get-routes";
import * as fs from "fs";
import * as path from "path";
import {DIRNAME} from "./important-paths";

const main = async () => {
    const routes = readRoutes()
    const routeListStatement = getRouteListStatement(routes)
    const linkToFnStatement = getLinkToFnForRoutesStatement(routes)

    const fileContent = `
// This file is auto-generated by src/meta/generate-helpers.ts
// Do not edit this file manually   
${routeListStatement}
${linkToFnStatement}
`

    const filePath = path.join(DIRNAME, "./__GENERATED__/routes.ts")

    fs.writeFileSync(filePath, fileContent)
}

main().then(() => {
    console.log("Done")
    process.exit(0)
})