
// This file is auto-generated by src/code-generators/generate-helpers.ts
// Do not edit this file manually   
export const routes = [
  "/assets/:id",
  "/assets",
  "/companies/:id",
  "/companies",
  "/",
  "/units/:id",
  "/units",
  "/users/:id",
  "/users",
  "/workorders/:id",
  "/workorders"
] as const
export const linkTo = ({"/assets/:id": ({id}: {id: string}) => `/assets/${id}`, "/assets": ({}: {}) => `/assets`, "/companies/:id": ({id}: {id: string}) => `/companies/${id}`, "/companies": ({}: {}) => `/companies`, "/": ({}: {}) => `/`, "/units/:id": ({id}: {id: string}) => `/units/${id}`, "/units": ({}: {}) => `/units`, "/users/:id": ({id}: {id: string}) => `/users/${id}`, "/users": ({}: {}) => `/users`, "/workorders/:id": ({id}: {id: string}) => `/workorders/${id}`, "/workorders": ({}: {}) => `/workorders`})
