// This file is auto-generated by src/meta/generate-helpers.ts
// Do not edit this file manually
export const routes = [
  "/assets",
  "/companies/:id",
  "/companies",
  "/",
  "/users",
] as const;
export const linkTo = {
  "/assets": ({}: {}) => `/assets`,
  "/companies/:id": ({ id }: { id: string }) => `/companies/${id}`,
  "/companies": ({}: {}) => `/companies`,
  "/": ({}: {}) => `/`,
  "/users": ({}: {}) => `/users`,
};
